[target.armv7-linux-androideabi]
image = "cross:armv7-linux-androideabi-0.2.1"

[build.env]
passthrough = [
    "V8_FROM_SOURCE",
    "SCCACHE_ERROR_LOG",
    "SCCACHE_LOG",
    "SCCACHE_DIR",
    "SCCACHE_IDLE_TIMEOUT"
]
