name: ci_android_v8

on:
  push:
    branches: [ "feat-version-0.61.0" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: git submodule update --init --recursive

    - run: sudo apt install libglib2.0-dev

    - run: rustup target add arm-unknown-linux-musleabihf

    - run: V8_FROM_SOURCE=1 cargo build -vv --release --target arm-unknown-linux-musleabihf

    - uses: actions/upload-artifact@v3
      with:
        name: librusty_v8_release_arm-unknown-linux-musleabihf.a
        path: target/arm-unknown-linux-musleabihf/release/gn_out/obj/librusty_v8.a